### PR TITLE
Only deploy crd conversion on unique app

### PR DESCRIPTION
**Pull request by tfussell**
When installed as a unique app, we would only like the conversion webhook deployment to be installed.

Towards https://github.com/giantswarm/giantswarm/issues/16382

### CODE REVIEW

**Comment by tfussell** [comment]
Let me know if you see a better way to do this.

**Comment by MarcelMue** [comment]
We still need the mutating/validating webhooks independent of the conversion. So this does not work

**Comment by tfussell** [comment]
> We still need the mutating/validating webhooks independent of the conversion. So this does not work

The idea was that mutating/validating webhooks can be selected by watch filter label so they should go to the controller matching the label. CRDs are cluster scoped so we thought it would make sense to deploy a unique instance of the controller solely for CRD conversion and configure the CRD to use it with `opsctl ensure crds`.

**Review by MarcelMue — APPROVED** [review]
I misread the PR initially, thinking it removed all webhooks unless running in unique

**Pull request merged**
